# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87fce22a709a7bf54728164cfe01cc1fe61b881b7fa2a9e83bb26715cdf1a825ce305eaf81f64c3341ef94b53a8eccaa81ab11becc59b9875b57dc163d4c4618

test:
  secret_key_base: dc097da8ab12f724c42552754f4d7e5d03408a847c4635a71d9ee825f118dd3c8cc60c01c449460d85be174fe12f9181f1dc69d41aeab2969e73c8bc50781ae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
